sudo: false
language: python
python:
  - 2.7
  - 3.5

cache:
  - pip

install:
  - make install_dev

script:
  - make test

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    on:
      branch: master
    local-dir: docs/build/html

  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: make publish

  - provider: releases
    skip-cleanup: true
    api_key: $GH_TOKEN
    on:
      tags: true
    file: dist/*
